### ISSUE TITLE
Plugin does not work with mkdocs 1.1

### ISSUE THREAD

**Issue by jhenninger** [rosscdh/mkdocs-markdownextradata-plugin#12]
It works fine with the previous version (1.0.4) but fails with 1.1. Running `mkdocs serve` results in the following error:

```
INFO    -  Building documentation... 
Traceback (most recent call last):
  File "/home/user/.local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/mkdocs/__main__.py", line 143, in serve_command
    **kwargs
  File "/home/user/.local/lib/python3.5/site-packages/mkdocs/commands/serve.py", line 141, in serve
    config = builder()
  File "/home/user/.local/lib/python3.5/site-packages/mkdocs/commands/serve.py", line 129, in builder
    **kwargs
  File "/home/user/.local/lib/python3.5/site-packages/mkdocs/config/base.py", line 197, in load_config
    errors, warnings = cfg.validate()
  File "/home/user/.local/lib/python3.5/site-packages/mkdocs/config/base.py", line 107, in validate
    run_failed, run_warnings = self._validate()
  File "/home/user/.local/lib/python3.5/site-packages/mkdocs/config/base.py", line 62, in _validate
    self[key] = config_option.validate(value)
  File "/home/user/.local/lib/python3.5/site-packages/mkdocs/config/config_options.py", line 130, in validate
    return self.run_validation(value)
  File "/home/user/.local/lib/python3.5/site-packages/mkdocs/config/config_options.py", line 591, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "/home/user/.local/lib/python3.5/site-packages/mkdocs/config/config_options.py", line 599, in load_plugin
    Plugin = self.installed_plugins[name].load()
  File "/home/user/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/home/user/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/user/.local/lib/python3.5/site-packages/markdownextradata/plugin.py", line 20, in <module>
    class MarkdownExtraDataPlugin(BasePlugin):
  File "/home/user/.local/lib/python3.5/site-packages/markdownextradata/plugin.py", line 26, in MarkdownExtraDataPlugin
    ('data', mkdocs.config.config_options.Type(mkdocs.utils.string_types, default=None)),
AttributeError: module 'mkdocs.utils' has no attribute 'string_types'

```

PS: Thank you for this awesome plugin!

**Comment by rosscdh** [comment]
Hey there,

I put a bit of time in this evening and could you try install https://pypi.org/project/mkdocs-markdownextradata-plugin/0.1.2/

Let me know how that goes for you!

**Comment by jhenninger** [comment]
It works, thank you for quick fix!

**Comment by rosscdh** [comment]
Thanks for reporting the issue! Good luck with your project!
